/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'
import { Route as ApiPublicCronWalletCleanupRouteImport } from './routes/api/public/cron/wallet-cleanup'
import { Route as ApiPublicCronHeartbeatRouteImport } from './routes/api/public/cron/heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronWalletCleanupRoute =
  ApiPublicCronWalletCleanupRouteImport.update({
    id: '/api/public/cron/wallet-cleanup',
    path: '/api/public/cron/wallet-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHeartbeatRoute = ApiPublicCronHeartbeatRouteImport.update({
  id: '/api/public/cron/heartbeat',
  path: '/api/public/cron/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron/heartbeat': typeof ApiPublicCronHeartbeatRoute
  '/api/public/cron/wallet-cleanup': typeof ApiPublicCronWalletCleanupRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron/heartbeat': typeof ApiPublicCronHeartbeatRoute
  '/api/public/cron/wallet-cleanup': typeof ApiPublicCronWalletCleanupRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron/heartbeat': typeof ApiPublicCronHeartbeatRoute
  '/api/public/cron/wallet-cleanup': typeof ApiPublicCronWalletCleanupRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/cron/heartbeat'
    | '/api/public/cron/wallet-cleanup'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/cron/heartbeat'
    | '/api/public/cron/wallet-cleanup'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/cron/heartbeat'
    | '/api/public/cron/wallet-cleanup'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronHeartbeatRoute: typeof ApiPublicCronHeartbeatRoute
  ApiPublicCronWalletCleanupRoute: typeof ApiPublicCronWalletCleanupRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/wallet-cleanup': {
      id: '/api/public/cron/wallet-cleanup'
      path: '/api/public/cron/wallet-cleanup'
      fullPath: '/api/public/cron/wallet-cleanup'
      preLoaderRoute: typeof ApiPublicCronWalletCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/heartbeat': {
      id: '/api/public/cron/heartbeat'
      path: '/api/public/cron/heartbeat'
      fullPath: '/api/public/cron/heartbeat'
      preLoaderRoute: typeof ApiPublicCronHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronHeartbeatRoute: ApiPublicCronHeartbeatRoute,
  ApiPublicCronWalletCleanupRoute: ApiPublicCronWalletCleanupRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
